const String SUPABASE_URL = 'https://lvjnjqaqipfcxqskohee.supabase.co';
const String SUPABASE_ANON_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2am5qcWFxaXBmY3hxc2tvaGVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODE2NTc3OTIsImV4cCI6MTk5NzIzMzc5Mn0.6wGvUEJ-vsxk2rX4eb8Z23rtwx17O-yoEMSJOUpbY6A';
